name: deploy-aws
on: [push]

jobs:
    deploy:
        name: Deploy to AWS
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v2
              
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                  aws-session-token: ${{ secrets.SESSION_TOKEN }}
                  aws-region: us-east-1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_wrapper: false

            - name: Terraform Apply
              run: |
                cd ./infra
                cd ./terraform-seller
                terraform init
                terraform plan
                terraform apply -auto-approve
                

          #  - name: Docker Hub 
           #   uses: docker/login-action@v2
            #  with:
             #   username: ${{ secrets.DHUB_USERNAME }}
              #  password: ${{ secrets.DHUB_PASSWORD }}

           # - name: Build Docker image
            #  run: docker build . -t ${{ secrets.DHUB_USERNAME }}/tickets-api:latest

            # - name: Push Docker image
             # run: docker push ${{ secrets.DHUB_USERNAME }}/tickets-api:latest

            

            - name: Create deployment
              run: |
                aws deploy create-deployment --application-name SellerInstance \
                    --deployment-config-name CodeDeployDefault.OneAtATime \
                    --deployment-group-name seller-group-pp \
                    --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=deployment.zip
